Improving README to add a warning about pip issue.
A fairly recent version of pip is required.

On old versions, the following error occurs:

skip_regex = options.skip_requirements_regex
AttributeError: 'NoneType' object has no attribute 'skip_requirements_regex'

Change-Id: I5cd2453a850398c77debbb494e3e0808d78369f5